spring:
  profiles:
    active: dev
  application:
    name: spring-boot

server:
  port: 8080

personal:
  name: keweizhou
  age: 25
  max: ${random.int(10)}
  uuid: ${random.uuid}
  hello: hello, i'm ${personal.name}, and ${personal.age}
# 配置文件格式
#  /{application}.yml
#  /{application}-{profile}.yml
#  /{label}/{application}-{profile}.yml
#  /{application}-{profile}.properties
#  /{label}/{application}-{profile}.properties
score:
  subject:
    math: 89
    chinese: 78
    english: 88
